#!/bin/sh

source /etc/swupdate/swupdate.env

exit_failure() {
        fw_setenv --script ${SWUPDATE_UBOOT_DIR}/install_failure.uenv
        finish
}

exit_success() {
        fw_setenv --script ${SWUPDATE_UBOOT_DIR}/install_success.uenv
        finish
}

finish() {
        fw_setenv --script ${SWUPDATE_UBOOT_DIR}/update_finished.uenv
        rm -f ${SWUPDATE_UPDATES_DIR}/*.swu
        exit
}


UPDATE_FILES=$(find ${SWUPDATE_UPDATES_DIR}/ -maxdepth 1 -name \*.swu  -type f | sort)
# Check if there are updates to install
if [ -z "${UPDATE_FILES}" ]; then
        echo "No update file to install."
        exit_failure
fi
# There are updates to install; proceed
for UPDATE_FILE in ${UPDATE_FILES}; do
        echo "Starting installation of ${UPDATE_FILE}"
        swupdate -f /etc/swupdate/swupdate.cfg -i "${UPDATE_FILE}"
        SWUPDATE_RESULT=$?
        if [ $SWUPDATE_RESULT -ne 0 ]; then
                echo "Installation of ${UPDATE_FILE} failed."
                exit_failure
        fi
done
echo "Installation of updates succeeded."
exit_success
